version: '3.7'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GEMINI_API_KEY=$GEMINI_API_KEY
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"